# Generated by Django 2.1.7 on 2024-07-23 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TumorApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='age',
            field=models.IntegerField(default=21, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='phonenumber',
            field=models.CharField(default='+919767345241', max_length=14),
        ),
        migrations.AddField(
            model_name='patient',
            name='sex',
            field=models.CharField(default='Male', max_length=6),
        ),
    ]
