# Generated by Django 2.1.7 on 2024-07-29 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TumorApp', '0003_admins'),
    ]

    operations = [
        migrations.AddField(
            model_name='admins',
            name='security_answer',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='admins',
            name='security_question',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
