# Generated by Django 2.1.7 on 2024-07-29 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TumorApp', '0004_auto_20240729_1152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admins',
            name='security_answer',
            field=models.CharField(default='chakri', max_length=255),
        ),
        migrations.AlterField(
            model_name='admins',
            name='security_question',
            field=models.CharField(default='what is your friend name? ', max_length=255),
        ),
    ]
