# Generated by Django 2.1.7 on 2024-07-30 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TumorApp', '0005_auto_20240729_1153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admins',
            name='username',
            field=models.CharField(max_length=40, unique=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
